### ISSUE TITLE
Runtime errors

### ISSUE THREAD

**Issue by darkoverlordofdata** [yihui/fun#7]
I tried both sourcing the code and install.packages('fun') and get the same results:

fun::mine_sweeper()
fun::lights_out()
Both get this errror:
Error in setGraphicsEventEnv(which, as.environment(list(...))) : 
  this graphics device does not support event handling

fun::sliding_puzzle()
Error in while ((len.right%%2) != (len.z%%2) | (all(z == z.right))) { : 
  argument is of length zero
  
fun::htmlspecialchars()
Error in gsub(x[i], subx[i], string, fixed = TRUE) : 
  argument "string" is missing, with no default

fun::tag_cloud()
Error in gsub(x[i], subx[i], string, fixed = TRUE) : 
  argument "tagData" is missing, with no default

The others are working.

**Comment by yihui** [comment]
What is your `sessionInfo()`? If you are not on Windows, you have to open an `x11` device with the argument `type = "Xlib"`, as shown on the help page `?fun::lights_out`.

**Comment by darkoverlordofdata** [comment]
Doh! Got it. Not used to seeing projects that use man pages :)
